spring.application.name=radioheaven-backend
spring.data.mongodb.uri=mongodb+srv://d7prasad89:F8Furh3uy21SJY80@cluster0.bulqz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=radioheaven
